export type BoardThemeName = 'blue' | 'brown' | 'green' | 'dark' | 'neo' | 'lichess' | 'chesscom';

export type PieceThemeName = 'alpha' | 'anarcandy' | 'caliente' | 'california' | 'cardinal' | 'cburnett' | 'celtic' | 'chess7' | 'chessnut' | 'classic' | 'companion' | 'cooke' | 'disguised' | 'dubrovny' | 'fantasy' | 'firi' | 'fresca' | 'gioco' | 'governor' | 'horsey' | 'icpieces' | 'kiwen-suwi' | 'kosal' | 'leipzig' | 'letter' | 'maestro' | 'merida' | 'monarchy' | 'mono' | 'mpchess' | 'neo' | 'pirouetti' | 'pixel' | 'reillycraig' | 'rhosgfx' | 'riohacha' | 'shapes' | 'spatial' | 'staunty' | 'tatiana' | 'xkcd';

export type PieceKey =
  | 'wK'
  | 'wQ'
  | 'wR'
  | 'wB'
  | 'wN'
  | 'wP'
  | 'bK'
  | 'bQ'
  | 'bR'
  | 'bB'
  | 'bN'
  | 'bP';

export type BoardTheme = {
  dark: string;
  frameDark: string;
  frameLight: string;
  highlight: string;
  label: string;
  light: string;
};

export const DEFAULT_BOARD_THEME: BoardThemeName = 'brown';
export const DEFAULT_PIECE_THEME: PieceThemeName = 'cburnett';

export const BOARD_THEMES: Record<BoardThemeName, BoardTheme> = {
  blue: {
    dark: '#93c5fd',
    frameDark: '#1e3a8a',
    frameLight: '#60a5fa',
    highlight: 'rgba(147, 197, 253, 0.62)',
    label: 'Blue',
    light: '#dbeafe',
  },
  brown: {
    dark: '#b88b4a',
    frameDark: '#8b5e34',
    frameLight: '#e0c598',
    highlight: 'rgba(255, 255, 255, 0.45)',
    label: 'Brown',
    light: '#f6e8c3',
  },
  green: {
    dark: '#a8cfa8',
    frameDark: '#27632a',
    frameLight: '#7fbf7f',
    highlight: 'rgba(168, 207, 168, 0.62)',
    label: 'Green',
    light: '#eaf5e3',
  },
  dark: {
    dark: '#222222',
    frameDark: '#111111',
    frameLight: '#5d5d5d',
    highlight: 'rgba(255, 255, 255, 0.32)',
    label: 'Dark',
    light: '#3b3b3b',
  },
  neo: {
    dark: '#c9c9c9',
    frameDark: '#7a7a7a',
    frameLight: '#e0e0e0',
    highlight: 'rgba(0, 0, 0, 0.16)',
    label: 'Neo',
    light: '#f4f4f4',
  },
  lichess: {
    dark: '#c2c2c2',
    frameDark: '#8b8b8b',
    frameLight: '#e3e3e3',
    highlight: 'rgba(100, 100, 100, 0.3)',
    label: 'Lichess',
    light: '#f3f3f3',
  },
  chesscom: {
    dark: '#7fa650',
    frameDark: '#5b7f36',
    frameLight: '#bcd39c',
    highlight: 'rgba(255, 255, 255, 0.42)',
    label: 'Chess.com',
    light: '#e1e8d0',
  },
};

export const BOARD_THEME_OPTIONS = Object.keys(BOARD_THEMES) as BoardThemeName[];

export const PIECE_THEME_OPTIONS: { id: PieceThemeName; label: string }[] = [
  { id: 'alpha', label: 'Alpha' },
  { id: 'anarcandy', label: 'Anarcandy' },
  { id: 'caliente', label: 'Caliente' },
  { id: 'california', label: 'California' },
  { id: 'cardinal', label: 'Cardinal' },
  { id: 'cburnett', label: 'Cburnett' },
  { id: 'celtic', label: 'Celtic' },
  { id: 'chess7', label: 'Chess 7' },
  { id: 'chessnut', label: 'Chessnut' },
  { id: 'classic', label: 'Classic' },
  { id: 'companion', label: 'Companion' },
  { id: 'cooke', label: 'Cooke' },
  { id: 'disguised', label: 'Disguised' },
  { id: 'dubrovny', label: 'Dubrovny' },
  { id: 'fantasy', label: 'Fantasy' },
  { id: 'firi', label: 'Firi' },
  { id: 'fresca', label: 'Fresca' },
  { id: 'gioco', label: 'Gioco' },
  { id: 'governor', label: 'Governor' },
  { id: 'horsey', label: 'Horsey' },
  { id: 'icpieces', label: 'IC Pieces' },
  { id: 'kiwen-suwi', label: 'Kiwen Suwi' },
  { id: 'kosal', label: 'Kosal' },
  { id: 'leipzig', label: 'Leipzig' },
  { id: 'letter', label: 'Letter' },
  { id: 'maestro', label: 'Maestro' },
  { id: 'merida', label: 'Merida' },
  { id: 'monarchy', label: 'Monarchy' },
  { id: 'mono', label: 'Mono' },
  { id: 'mpchess', label: 'MP Chess' },
  { id: 'neo', label: 'Neo' },
  { id: 'pirouetti', label: 'Pirouetti' },
  { id: 'pixel', label: 'Pixel' },
  { id: 'reillycraig', label: 'Reilly Craig' },
  { id: 'rhosgfx', label: 'Rhosgfx' },
  { id: 'riohacha', label: 'Riohacha' },
  { id: 'shapes', label: 'Shapes' },
  { id: 'spatial', label: 'Spatial' },
  { id: 'staunty', label: 'Staunty' },
  { id: 'tatiana', label: 'Tatiana' },
  { id: 'xkcd', label: 'XKCD' },
];

export const PIECE_ASSETS: Record<PieceThemeName, Record<PieceKey, number>> = {
  alpha: {
    wK: require('../../assets/pieces/alpha/wK.svg'),
    wQ: require('../../assets/pieces/alpha/wQ.svg'),
    wR: require('../../assets/pieces/alpha/wR.svg'),
    wB: require('../../assets/pieces/alpha/wB.svg'),
    wN: require('../../assets/pieces/alpha/wN.svg'),
    wP: require('../../assets/pieces/alpha/wP.svg'),
    bK: require('../../assets/pieces/alpha/bK.svg'),
    bQ: require('../../assets/pieces/alpha/bQ.svg'),
    bR: require('../../assets/pieces/alpha/bR.svg'),
    bB: require('../../assets/pieces/alpha/bB.svg'),
    bN: require('../../assets/pieces/alpha/bN.svg'),
    bP: require('../../assets/pieces/alpha/bP.svg'),
  },
  anarcandy: {
    wK: require('../../assets/pieces/anarcandy/wK.svg'),
    wQ: require('../../assets/pieces/anarcandy/wQ.svg'),
    wR: require('../../assets/pieces/anarcandy/wR.svg'),
    wB: require('../../assets/pieces/anarcandy/wB.svg'),
    wN: require('../../assets/pieces/anarcandy/wN.svg'),
    wP: require('../../assets/pieces/anarcandy/wP.svg'),
    bK: require('../../assets/pieces/anarcandy/bK.svg'),
    bQ: require('../../assets/pieces/anarcandy/bQ.svg'),
    bR: require('../../assets/pieces/anarcandy/bR.svg'),
    bB: require('../../assets/pieces/anarcandy/bB.svg'),
    bN: require('../../assets/pieces/anarcandy/bN.svg'),
    bP: require('../../assets/pieces/anarcandy/bP.svg'),
  },
  caliente: {
    wK: require('../../assets/pieces/caliente/wK.svg'),
    wQ: require('../../assets/pieces/caliente/wQ.svg'),
    wR: require('../../assets/pieces/caliente/wR.svg'),
    wB: require('../../assets/pieces/caliente/wB.svg'),
    wN: require('../../assets/pieces/caliente/wN.svg'),
    wP: require('../../assets/pieces/caliente/wP.svg'),
    bK: require('../../assets/pieces/caliente/bK.svg'),
    bQ: require('../../assets/pieces/caliente/bQ.svg'),
    bR: require('../../assets/pieces/caliente/bR.svg'),
    bB: require('../../assets/pieces/caliente/bB.svg'),
    bN: require('../../assets/pieces/caliente/bN.svg'),
    bP: require('../../assets/pieces/caliente/bP.svg'),
  },
  california: {
    wK: require('../../assets/pieces/california/wK.svg'),
    wQ: require('../../assets/pieces/california/wQ.svg'),
    wR: require('../../assets/pieces/california/wR.svg'),
    wB: require('../../assets/pieces/california/wB.svg'),
    wN: require('../../assets/pieces/california/wN.svg'),
    wP: require('../../assets/pieces/california/wP.svg'),
    bK: require('../../assets/pieces/california/bK.svg'),
    bQ: require('../../assets/pieces/california/bQ.svg'),
    bR: require('../../assets/pieces/california/bR.svg'),
    bB: require('../../assets/pieces/california/bB.svg'),
    bN: require('../../assets/pieces/california/bN.svg'),
    bP: require('../../assets/pieces/california/bP.svg'),
  },
  cardinal: {
    wK: require('../../assets/pieces/cardinal/wK.svg'),
    wQ: require('../../assets/pieces/cardinal/wQ.svg'),
    wR: require('../../assets/pieces/cardinal/wR.svg'),
    wB: require('../../assets/pieces/cardinal/wB.svg'),
    wN: require('../../assets/pieces/cardinal/wN.svg'),
    wP: require('../../assets/pieces/cardinal/wP.svg'),
    bK: require('../../assets/pieces/cardinal/bK.svg'),
    bQ: require('../../assets/pieces/cardinal/bQ.svg'),
    bR: require('../../assets/pieces/cardinal/bR.svg'),
    bB: require('../../assets/pieces/cardinal/bB.svg'),
    bN: require('../../assets/pieces/cardinal/bN.svg'),
    bP: require('../../assets/pieces/cardinal/bP.svg'),
  },
  cburnett: {
    wK: require('../../assets/pieces/cburnett/wK.svg'),
    wQ: require('../../assets/pieces/cburnett/wQ.svg'),
    wR: require('../../assets/pieces/cburnett/wR.svg'),
    wB: require('../../assets/pieces/cburnett/wB.svg'),
    wN: require('../../assets/pieces/cburnett/wN.svg'),
    wP: require('../../assets/pieces/cburnett/wP.svg'),
    bK: require('../../assets/pieces/cburnett/bK.svg'),
    bQ: require('../../assets/pieces/cburnett/bQ.svg'),
    bR: require('../../assets/pieces/cburnett/bR.svg'),
    bB: require('../../assets/pieces/cburnett/bB.svg'),
    bN: require('../../assets/pieces/cburnett/bN.svg'),
    bP: require('../../assets/pieces/cburnett/bP.svg'),
  },
  celtic: {
    wK: require('../../assets/pieces/celtic/wK.svg'),
    wQ: require('../../assets/pieces/celtic/wQ.svg'),
    wR: require('../../assets/pieces/celtic/wR.svg'),
    wB: require('../../assets/pieces/celtic/wB.svg'),
    wN: require('../../assets/pieces/celtic/wN.svg'),
    wP: require('../../assets/pieces/celtic/wP.svg'),
    bK: require('../../assets/pieces/celtic/bK.svg'),
    bQ: require('../../assets/pieces/celtic/bQ.svg'),
    bR: require('../../assets/pieces/celtic/bR.svg'),
    bB: require('../../assets/pieces/celtic/bB.svg'),
    bN: require('../../assets/pieces/celtic/bN.svg'),
    bP: require('../../assets/pieces/celtic/bP.svg'),
  },
  chess7: {
    wK: require('../../assets/pieces/chess7/wK.svg'),
    wQ: require('../../assets/pieces/chess7/wQ.svg'),
    wR: require('../../assets/pieces/chess7/wR.svg'),
    wB: require('../../assets/pieces/chess7/wB.svg'),
    wN: require('../../assets/pieces/chess7/wN.svg'),
    wP: require('../../assets/pieces/chess7/wP.svg'),
    bK: require('../../assets/pieces/chess7/bK.svg'),
    bQ: require('../../assets/pieces/chess7/bQ.svg'),
    bR: require('../../assets/pieces/chess7/bR.svg'),
    bB: require('../../assets/pieces/chess7/bB.svg'),
    bN: require('../../assets/pieces/chess7/bN.svg'),
    bP: require('../../assets/pieces/chess7/bP.svg'),
  },
  chessnut: {
    wK: require('../../assets/pieces/chessnut/wK.svg'),
    wQ: require('../../assets/pieces/chessnut/wQ.svg'),
    wR: require('../../assets/pieces/chessnut/wR.svg'),
    wB: require('../../assets/pieces/chessnut/wB.svg'),
    wN: require('../../assets/pieces/chessnut/wN.svg'),
    wP: require('../../assets/pieces/chessnut/wP.svg'),
    bK: require('../../assets/pieces/chessnut/bK.svg'),
    bQ: require('../../assets/pieces/chessnut/bQ.svg'),
    bR: require('../../assets/pieces/chessnut/bR.svg'),
    bB: require('../../assets/pieces/chessnut/bB.svg'),
    bN: require('../../assets/pieces/chessnut/bN.svg'),
    bP: require('../../assets/pieces/chessnut/bP.svg'),
  },
  classic: {
    wK: require('../../assets/pieces/classic/wK.svg'),
    wQ: require('../../assets/pieces/classic/wQ.svg'),
    wR: require('../../assets/pieces/classic/wR.svg'),
    wB: require('../../assets/pieces/classic/wB.svg'),
    wN: require('../../assets/pieces/classic/wN.svg'),
    wP: require('../../assets/pieces/classic/wP.svg'),
    bK: require('../../assets/pieces/classic/bK.svg'),
    bQ: require('../../assets/pieces/classic/bQ.svg'),
    bR: require('../../assets/pieces/classic/bR.svg'),
    bB: require('../../assets/pieces/classic/bB.svg'),
    bN: require('../../assets/pieces/classic/bN.svg'),
    bP: require('../../assets/pieces/classic/bP.svg'),
  },
  companion: {
    wK: require('../../assets/pieces/companion/wK.svg'),
    wQ: require('../../assets/pieces/companion/wQ.svg'),
    wR: require('../../assets/pieces/companion/wR.svg'),
    wB: require('../../assets/pieces/companion/wB.svg'),
    wN: require('../../assets/pieces/companion/wN.svg'),
    wP: require('../../assets/pieces/companion/wP.svg'),
    bK: require('../../assets/pieces/companion/bK.svg'),
    bQ: require('../../assets/pieces/companion/bQ.svg'),
    bR: require('../../assets/pieces/companion/bR.svg'),
    bB: require('../../assets/pieces/companion/bB.svg'),
    bN: require('../../assets/pieces/companion/bN.svg'),
    bP: require('../../assets/pieces/companion/bP.svg'),
  },
  cooke: {
    wK: require('../../assets/pieces/cooke/wK.svg'),
    wQ: require('../../assets/pieces/cooke/wQ.svg'),
    wR: require('../../assets/pieces/cooke/wR.svg'),
    wB: require('../../assets/pieces/cooke/wB.svg'),
    wN: require('../../assets/pieces/cooke/wN.svg'),
    wP: require('../../assets/pieces/cooke/wP.svg'),
    bK: require('../../assets/pieces/cooke/bK.svg'),
    bQ: require('../../assets/pieces/cooke/bQ.svg'),
    bR: require('../../assets/pieces/cooke/bR.svg'),
    bB: require('../../assets/pieces/cooke/bB.svg'),
    bN: require('../../assets/pieces/cooke/bN.svg'),
    bP: require('../../assets/pieces/cooke/bP.svg'),
  },
  disguised: {
    wK: require('../../assets/pieces/disguised/w.svg'),
    wQ: require('../../assets/pieces/disguised/w.svg'),
    wR: require('../../assets/pieces/disguised/w.svg'),
    wB: require('../../assets/pieces/disguised/w.svg'),
    wN: require('../../assets/pieces/disguised/w.svg'),
    wP: require('../../assets/pieces/disguised/w.svg'),
    bK: require('../../assets/pieces/disguised/b.svg'),
    bQ: require('../../assets/pieces/disguised/b.svg'),
    bR: require('../../assets/pieces/disguised/b.svg'),
    bB: require('../../assets/pieces/disguised/b.svg'),
    bN: require('../../assets/pieces/disguised/b.svg'),
    bP: require('../../assets/pieces/disguised/b.svg'),
  },
  dubrovny: {
    wK: require('../../assets/pieces/dubrovny/wK.svg'),
    wQ: require('../../assets/pieces/dubrovny/wQ.svg'),
    wR: require('../../assets/pieces/dubrovny/wR.svg'),
    wB: require('../../assets/pieces/dubrovny/wB.svg'),
    wN: require('../../assets/pieces/dubrovny/wN.svg'),
    wP: require('../../assets/pieces/dubrovny/wP.svg'),
    bK: require('../../assets/pieces/dubrovny/bK.svg'),
    bQ: require('../../assets/pieces/dubrovny/bQ.svg'),
    bR: require('../../assets/pieces/dubrovny/bR.svg'),
    bB: require('../../assets/pieces/dubrovny/bB.svg'),
    bN: require('../../assets/pieces/dubrovny/bN.svg'),
    bP: require('../../assets/pieces/dubrovny/bP.svg'),
  },
  fantasy: {
    wK: require('../../assets/pieces/fantasy/wK.svg'),
    wQ: require('../../assets/pieces/fantasy/wQ.svg'),
    wR: require('../../assets/pieces/fantasy/wR.svg'),
    wB: require('../../assets/pieces/fantasy/wB.svg'),
    wN: require('../../assets/pieces/fantasy/wN.svg'),
    wP: require('../../assets/pieces/fantasy/wP.svg'),
    bK: require('../../assets/pieces/fantasy/bK.svg'),
    bQ: require('../../assets/pieces/fantasy/bQ.svg'),
    bR: require('../../assets/pieces/fantasy/bR.svg'),
    bB: require('../../assets/pieces/fantasy/bB.svg'),
    bN: require('../../assets/pieces/fantasy/bN.svg'),
    bP: require('../../assets/pieces/fantasy/bP.svg'),
  },
  firi: {
    wK: require('../../assets/pieces/firi/wK.svg'),
    wQ: require('../../assets/pieces/firi/wQ.svg'),
    wR: require('../../assets/pieces/firi/wR.svg'),
    wB: require('../../assets/pieces/firi/wB.svg'),
    wN: require('../../assets/pieces/firi/wN.svg'),
    wP: require('../../assets/pieces/firi/wP.svg'),
    bK: require('../../assets/pieces/firi/bK.svg'),
    bQ: require('../../assets/pieces/firi/bQ.svg'),
    bR: require('../../assets/pieces/firi/bR.svg'),
    bB: require('../../assets/pieces/firi/bB.svg'),
    bN: require('../../assets/pieces/firi/bN.svg'),
    bP: require('../../assets/pieces/firi/bP.svg'),
  },
  fresca: {
    wK: require('../../assets/pieces/fresca/wK.svg'),
    wQ: require('../../assets/pieces/fresca/wQ.svg'),
    wR: require('../../assets/pieces/fresca/wR.svg'),
    wB: require('../../assets/pieces/fresca/wB.svg'),
    wN: require('../../assets/pieces/fresca/wN.svg'),
    wP: require('../../assets/pieces/fresca/wP.svg'),
    bK: require('../../assets/pieces/fresca/bK.svg'),
    bQ: require('../../assets/pieces/fresca/bQ.svg'),
    bR: require('../../assets/pieces/fresca/bR.svg'),
    bB: require('../../assets/pieces/fresca/bB.svg'),
    bN: require('../../assets/pieces/fresca/bN.svg'),
    bP: require('../../assets/pieces/fresca/bP.svg'),
  },
  gioco: {
    wK: require('../../assets/pieces/gioco/wK.svg'),
    wQ: require('../../assets/pieces/gioco/wQ.svg'),
    wR: require('../../assets/pieces/gioco/wR.svg'),
    wB: require('../../assets/pieces/gioco/wB.svg'),
    wN: require('../../assets/pieces/gioco/wN.svg'),
    wP: require('../../assets/pieces/gioco/wP.svg'),
    bK: require('../../assets/pieces/gioco/bK.svg'),
    bQ: require('../../assets/pieces/gioco/bQ.svg'),
    bR: require('../../assets/pieces/gioco/bR.svg'),
    bB: require('../../assets/pieces/gioco/bB.svg'),
    bN: require('../../assets/pieces/gioco/bN.svg'),
    bP: require('../../assets/pieces/gioco/bP.svg'),
  },
  governor: {
    wK: require('../../assets/pieces/governor/wK.svg'),
    wQ: require('../../assets/pieces/governor/wQ.svg'),
    wR: require('../../assets/pieces/governor/wR.svg'),
    wB: require('../../assets/pieces/governor/wB.svg'),
    wN: require('../../assets/pieces/governor/wN.svg'),
    wP: require('../../assets/pieces/governor/wP.svg'),
    bK: require('../../assets/pieces/governor/bK.svg'),
    bQ: require('../../assets/pieces/governor/bQ.svg'),
    bR: require('../../assets/pieces/governor/bR.svg'),
    bB: require('../../assets/pieces/governor/bB.svg'),
    bN: require('../../assets/pieces/governor/bN.svg'),
    bP: require('../../assets/pieces/governor/bP.svg'),
  },
  horsey: {
    wK: require('../../assets/pieces/horsey/wK.svg'),
    wQ: require('../../assets/pieces/horsey/wQ.svg'),
    wR: require('../../assets/pieces/horsey/wR.svg'),
    wB: require('../../assets/pieces/horsey/wB.svg'),
    wN: require('../../assets/pieces/horsey/wN.svg'),
    wP: require('../../assets/pieces/horsey/wP.svg'),
    bK: require('../../assets/pieces/horsey/bK.svg'),
    bQ: require('../../assets/pieces/horsey/bQ.svg'),
    bR: require('../../assets/pieces/horsey/bR.svg'),
    bB: require('../../assets/pieces/horsey/bB.svg'),
    bN: require('../../assets/pieces/horsey/bN.svg'),
    bP: require('../../assets/pieces/horsey/bP.svg'),
  },
  icpieces: {
    wK: require('../../assets/pieces/icpieces/wK.svg'),
    wQ: require('../../assets/pieces/icpieces/wQ.svg'),
    wR: require('../../assets/pieces/icpieces/wR.svg'),
    wB: require('../../assets/pieces/icpieces/wB.svg'),
    wN: require('../../assets/pieces/icpieces/wN.svg'),
    wP: require('../../assets/pieces/icpieces/wP.svg'),
    bK: require('../../assets/pieces/icpieces/bK.svg'),
    bQ: require('../../assets/pieces/icpieces/bQ.svg'),
    bR: require('../../assets/pieces/icpieces/bR.svg'),
    bB: require('../../assets/pieces/icpieces/bB.svg'),
    bN: require('../../assets/pieces/icpieces/bN.svg'),
    bP: require('../../assets/pieces/icpieces/bP.svg'),
  },
  'kiwen-suwi': {
    wK: require('../../assets/pieces/kiwen-suwi/wK.svg'),
    wQ: require('../../assets/pieces/kiwen-suwi/wQ.svg'),
    wR: require('../../assets/pieces/kiwen-suwi/wR.svg'),
    wB: require('../../assets/pieces/kiwen-suwi/wB.svg'),
    wN: require('../../assets/pieces/kiwen-suwi/wN.svg'),
    wP: require('../../assets/pieces/kiwen-suwi/wP.svg'),
    bK: require('../../assets/pieces/kiwen-suwi/bK.svg'),
    bQ: require('../../assets/pieces/kiwen-suwi/bQ.svg'),
    bR: require('../../assets/pieces/kiwen-suwi/bR.svg'),
    bB: require('../../assets/pieces/kiwen-suwi/bB.svg'),
    bN: require('../../assets/pieces/kiwen-suwi/bN.svg'),
    bP: require('../../assets/pieces/kiwen-suwi/bP.svg'),
  },
  kosal: {
    wK: require('../../assets/pieces/kosal/wK.svg'),
    wQ: require('../../assets/pieces/kosal/wQ.svg'),
    wR: require('../../assets/pieces/kosal/wR.svg'),
    wB: require('../../assets/pieces/kosal/wB.svg'),
    wN: require('../../assets/pieces/kosal/wN.svg'),
    wP: require('../../assets/pieces/kosal/wP.svg'),
    bK: require('../../assets/pieces/kosal/bK.svg'),
    bQ: require('../../assets/pieces/kosal/bQ.svg'),
    bR: require('../../assets/pieces/kosal/bR.svg'),
    bB: require('../../assets/pieces/kosal/bB.svg'),
    bN: require('../../assets/pieces/kosal/bN.svg'),
    bP: require('../../assets/pieces/kosal/bP.svg'),
  },
  leipzig: {
    wK: require('../../assets/pieces/leipzig/wK.svg'),
    wQ: require('../../assets/pieces/leipzig/wQ.svg'),
    wR: require('../../assets/pieces/leipzig/wR.svg'),
    wB: require('../../assets/pieces/leipzig/wB.svg'),
    wN: require('../../assets/pieces/leipzig/wN.svg'),
    wP: require('../../assets/pieces/leipzig/wP.svg'),
    bK: require('../../assets/pieces/leipzig/bK.svg'),
    bQ: require('../../assets/pieces/leipzig/bQ.svg'),
    bR: require('../../assets/pieces/leipzig/bR.svg'),
    bB: require('../../assets/pieces/leipzig/bB.svg'),
    bN: require('../../assets/pieces/leipzig/bN.svg'),
    bP: require('../../assets/pieces/leipzig/bP.svg'),
  },
  letter: {
    wK: require('../../assets/pieces/letter/wK.svg'),
    wQ: require('../../assets/pieces/letter/wQ.svg'),
    wR: require('../../assets/pieces/letter/wR.svg'),
    wB: require('../../assets/pieces/letter/wB.svg'),
    wN: require('../../assets/pieces/letter/wN.svg'),
    wP: require('../../assets/pieces/letter/wP.svg'),
    bK: require('../../assets/pieces/letter/bK.svg'),
    bQ: require('../../assets/pieces/letter/bQ.svg'),
    bR: require('../../assets/pieces/letter/bR.svg'),
    bB: require('../../assets/pieces/letter/bB.svg'),
    bN: require('../../assets/pieces/letter/bN.svg'),
    bP: require('../../assets/pieces/letter/bP.svg'),
  },
  maestro: {
    wK: require('../../assets/pieces/maestro/wK.svg'),
    wQ: require('../../assets/pieces/maestro/wQ.svg'),
    wR: require('../../assets/pieces/maestro/wR.svg'),
    wB: require('../../assets/pieces/maestro/wB.svg'),
    wN: require('../../assets/pieces/maestro/wN.svg'),
    wP: require('../../assets/pieces/maestro/wP.svg'),
    bK: require('../../assets/pieces/maestro/bK.svg'),
    bQ: require('../../assets/pieces/maestro/bQ.svg'),
    bR: require('../../assets/pieces/maestro/bR.svg'),
    bB: require('../../assets/pieces/maestro/bB.svg'),
    bN: require('../../assets/pieces/maestro/bN.svg'),
    bP: require('../../assets/pieces/maestro/bP.svg'),
  },
  merida: {
    wK: require('../../assets/pieces/merida/wK.svg'),
    wQ: require('../../assets/pieces/merida/wQ.svg'),
    wR: require('../../assets/pieces/merida/wR.svg'),
    wB: require('../../assets/pieces/merida/wB.svg'),
    wN: require('../../assets/pieces/merida/wN.svg'),
    wP: require('../../assets/pieces/merida/wP.svg'),
    bK: require('../../assets/pieces/merida/bK.svg'),
    bQ: require('../../assets/pieces/merida/bQ.svg'),
    bR: require('../../assets/pieces/merida/bR.svg'),
    bB: require('../../assets/pieces/merida/bB.svg'),
    bN: require('../../assets/pieces/merida/bN.svg'),
    bP: require('../../assets/pieces/merida/bP.svg'),
  },
  monarchy: {
    wK: require('../../assets/pieces/monarchy/wK.webp'),
    wQ: require('../../assets/pieces/monarchy/wQ.webp'),
    wR: require('../../assets/pieces/monarchy/wR.webp'),
    wB: require('../../assets/pieces/monarchy/wB.webp'),
    wN: require('../../assets/pieces/monarchy/wN.webp'),
    wP: require('../../assets/pieces/monarchy/wP.webp'),
    bK: require('../../assets/pieces/monarchy/bK.webp'),
    bQ: require('../../assets/pieces/monarchy/bQ.webp'),
    bR: require('../../assets/pieces/monarchy/bR.webp'),
    bB: require('../../assets/pieces/monarchy/bB.webp'),
    bN: require('../../assets/pieces/monarchy/bN.webp'),
    bP: require('../../assets/pieces/monarchy/bP.webp'),
  },
  mono: {
    wK: require('../../assets/pieces/mono/K.svg'),
    wQ: require('../../assets/pieces/mono/Q.svg'),
    wR: require('../../assets/pieces/mono/R.svg'),
    wB: require('../../assets/pieces/mono/B.svg'),
    wN: require('../../assets/pieces/mono/N.svg'),
    wP: require('../../assets/pieces/mono/P.svg'),
    bK: require('../../assets/pieces/mono/K.svg'),
    bQ: require('../../assets/pieces/mono/Q.svg'),
    bR: require('../../assets/pieces/mono/R.svg'),
    bB: require('../../assets/pieces/mono/B.svg'),
    bN: require('../../assets/pieces/mono/N.svg'),
    bP: require('../../assets/pieces/mono/P.svg'),
  },
  mpchess: {
    wK: require('../../assets/pieces/mpchess/wK.svg'),
    wQ: require('../../assets/pieces/mpchess/wQ.svg'),
    wR: require('../../assets/pieces/mpchess/wR.svg'),
    wB: require('../../assets/pieces/mpchess/wB.svg'),
    wN: require('../../assets/pieces/mpchess/wN.svg'),
    wP: require('../../assets/pieces/mpchess/wP.svg'),
    bK: require('../../assets/pieces/mpchess/bK.svg'),
    bQ: require('../../assets/pieces/mpchess/bQ.svg'),
    bR: require('../../assets/pieces/mpchess/bR.svg'),
    bB: require('../../assets/pieces/mpchess/bB.svg'),
    bN: require('../../assets/pieces/mpchess/bN.svg'),
    bP: require('../../assets/pieces/mpchess/bP.svg'),
  },
  neo: {
    wK: require('../../assets/pieces/neo/wK.svg'),
    wQ: require('../../assets/pieces/neo/wQ.svg'),
    wR: require('../../assets/pieces/neo/wR.svg'),
    wB: require('../../assets/pieces/neo/wB.svg'),
    wN: require('../../assets/pieces/neo/wN.svg'),
    wP: require('../../assets/pieces/neo/wP.svg'),
    bK: require('../../assets/pieces/neo/bK.svg'),
    bQ: require('../../assets/pieces/neo/bQ.svg'),
    bR: require('../../assets/pieces/neo/bR.svg'),
    bB: require('../../assets/pieces/neo/bB.svg'),
    bN: require('../../assets/pieces/neo/bN.svg'),
    bP: require('../../assets/pieces/neo/bP.svg'),
  },
  pirouetti: {
    wK: require('../../assets/pieces/pirouetti/wK.svg'),
    wQ: require('../../assets/pieces/pirouetti/wQ.svg'),
    wR: require('../../assets/pieces/pirouetti/wR.svg'),
    wB: require('../../assets/pieces/pirouetti/wB.svg'),
    wN: require('../../assets/pieces/pirouetti/wN.svg'),
    wP: require('../../assets/pieces/pirouetti/wP.svg'),
    bK: require('../../assets/pieces/pirouetti/bK.svg'),
    bQ: require('../../assets/pieces/pirouetti/bQ.svg'),
    bR: require('../../assets/pieces/pirouetti/bR.svg'),
    bB: require('../../assets/pieces/pirouetti/bB.svg'),
    bN: require('../../assets/pieces/pirouetti/bN.svg'),
    bP: require('../../assets/pieces/pirouetti/bP.svg'),
  },
  pixel: {
    wK: require('../../assets/pieces/pixel/wK.svg'),
    wQ: require('../../assets/pieces/pixel/wQ.svg'),
    wR: require('../../assets/pieces/pixel/wR.svg'),
    wB: require('../../assets/pieces/pixel/wB.svg'),
    wN: require('../../assets/pieces/pixel/wN.svg'),
    wP: require('../../assets/pieces/pixel/wP.svg'),
    bK: require('../../assets/pieces/pixel/bK.svg'),
    bQ: require('../../assets/pieces/pixel/bQ.svg'),
    bR: require('../../assets/pieces/pixel/bR.svg'),
    bB: require('../../assets/pieces/pixel/bB.svg'),
    bN: require('../../assets/pieces/pixel/bN.svg'),
    bP: require('../../assets/pieces/pixel/bP.svg'),
  },
  reillycraig: {
    wK: require('../../assets/pieces/reillycraig/wK.svg'),
    wQ: require('../../assets/pieces/reillycraig/wQ.svg'),
    wR: require('../../assets/pieces/reillycraig/wR.svg'),
    wB: require('../../assets/pieces/reillycraig/wB.svg'),
    wN: require('../../assets/pieces/reillycraig/wN.svg'),
    wP: require('../../assets/pieces/reillycraig/wP.svg'),
    bK: require('../../assets/pieces/reillycraig/bK.svg'),
    bQ: require('../../assets/pieces/reillycraig/bQ.svg'),
    bR: require('../../assets/pieces/reillycraig/bR.svg'),
    bB: require('../../assets/pieces/reillycraig/bB.svg'),
    bN: require('../../assets/pieces/reillycraig/bN.svg'),
    bP: require('../../assets/pieces/reillycraig/bP.svg'),
  },
  rhosgfx: {
    wK: require('../../assets/pieces/rhosgfx/wK.svg'),
    wQ: require('../../assets/pieces/rhosgfx/wQ.svg'),
    wR: require('../../assets/pieces/rhosgfx/wR.svg'),
    wB: require('../../assets/pieces/rhosgfx/wB.svg'),
    wN: require('../../assets/pieces/rhosgfx/wN.svg'),
    wP: require('../../assets/pieces/rhosgfx/wP.svg'),
    bK: require('../../assets/pieces/rhosgfx/bK.svg'),
    bQ: require('../../assets/pieces/rhosgfx/bQ.svg'),
    bR: require('../../assets/pieces/rhosgfx/bR.svg'),
    bB: require('../../assets/pieces/rhosgfx/bB.svg'),
    bN: require('../../assets/pieces/rhosgfx/bN.svg'),
    bP: require('../../assets/pieces/rhosgfx/bP.svg'),
  },
  riohacha: {
    wK: require('../../assets/pieces/riohacha/wK.svg'),
    wQ: require('../../assets/pieces/riohacha/wQ.svg'),
    wR: require('../../assets/pieces/riohacha/wR.svg'),
    wB: require('../../assets/pieces/riohacha/wB.svg'),
    wN: require('../../assets/pieces/riohacha/wN.svg'),
    wP: require('../../assets/pieces/riohacha/wP.svg'),
    bK: require('../../assets/pieces/riohacha/bK.svg'),
    bQ: require('../../assets/pieces/riohacha/bQ.svg'),
    bR: require('../../assets/pieces/riohacha/bR.svg'),
    bB: require('../../assets/pieces/riohacha/bB.svg'),
    bN: require('../../assets/pieces/riohacha/bN.svg'),
    bP: require('../../assets/pieces/riohacha/bP.svg'),
  },
  shapes: {
    wK: require('../../assets/pieces/shapes/wK.svg'),
    wQ: require('../../assets/pieces/shapes/wQ.svg'),
    wR: require('../../assets/pieces/shapes/wR.svg'),
    wB: require('../../assets/pieces/shapes/wB.svg'),
    wN: require('../../assets/pieces/shapes/wN.svg'),
    wP: require('../../assets/pieces/shapes/wP.svg'),
    bK: require('../../assets/pieces/shapes/bK.svg'),
    bQ: require('../../assets/pieces/shapes/bQ.svg'),
    bR: require('../../assets/pieces/shapes/bR.svg'),
    bB: require('../../assets/pieces/shapes/bB.svg'),
    bN: require('../../assets/pieces/shapes/bN.svg'),
    bP: require('../../assets/pieces/shapes/bP.svg'),
  },
  spatial: {
    wK: require('../../assets/pieces/spatial/wK.svg'),
    wQ: require('../../assets/pieces/spatial/wQ.svg'),
    wR: require('../../assets/pieces/spatial/wR.svg'),
    wB: require('../../assets/pieces/spatial/wB.svg'),
    wN: require('../../assets/pieces/spatial/wN.svg'),
    wP: require('../../assets/pieces/spatial/wP.svg'),
    bK: require('../../assets/pieces/spatial/bK.svg'),
    bQ: require('../../assets/pieces/spatial/bQ.svg'),
    bR: require('../../assets/pieces/spatial/bR.svg'),
    bB: require('../../assets/pieces/spatial/bB.svg'),
    bN: require('../../assets/pieces/spatial/bN.svg'),
    bP: require('../../assets/pieces/spatial/bP.svg'),
  },
  staunty: {
    wK: require('../../assets/pieces/staunty/wK.svg'),
    wQ: require('../../assets/pieces/staunty/wQ.svg'),
    wR: require('../../assets/pieces/staunty/wR.svg'),
    wB: require('../../assets/pieces/staunty/wB.svg'),
    wN: require('../../assets/pieces/staunty/wN.svg'),
    wP: require('../../assets/pieces/staunty/wP.svg'),
    bK: require('../../assets/pieces/staunty/bK.svg'),
    bQ: require('../../assets/pieces/staunty/bQ.svg'),
    bR: require('../../assets/pieces/staunty/bR.svg'),
    bB: require('../../assets/pieces/staunty/bB.svg'),
    bN: require('../../assets/pieces/staunty/bN.svg'),
    bP: require('../../assets/pieces/staunty/bP.svg'),
  },
  tatiana: {
    wK: require('../../assets/pieces/tatiana/wK.svg'),
    wQ: require('../../assets/pieces/tatiana/wQ.svg'),
    wR: require('../../assets/pieces/tatiana/wR.svg'),
    wB: require('../../assets/pieces/tatiana/wB.svg'),
    wN: require('../../assets/pieces/tatiana/wN.svg'),
    wP: require('../../assets/pieces/tatiana/wP.svg'),
    bK: require('../../assets/pieces/tatiana/bK.svg'),
    bQ: require('../../assets/pieces/tatiana/bQ.svg'),
    bR: require('../../assets/pieces/tatiana/bR.svg'),
    bB: require('../../assets/pieces/tatiana/bB.svg'),
    bN: require('../../assets/pieces/tatiana/bN.svg'),
    bP: require('../../assets/pieces/tatiana/bP.svg'),
  },
  xkcd: {
    wK: require('../../assets/pieces/xkcd/wK.svg'),
    wQ: require('../../assets/pieces/xkcd/wQ.svg'),
    wR: require('../../assets/pieces/xkcd/wR.svg'),
    wB: require('../../assets/pieces/xkcd/wB.svg'),
    wN: require('../../assets/pieces/xkcd/wN.svg'),
    wP: require('../../assets/pieces/xkcd/wP.svg'),
    bK: require('../../assets/pieces/xkcd/bK.svg'),
    bQ: require('../../assets/pieces/xkcd/bQ.svg'),
    bR: require('../../assets/pieces/xkcd/bR.svg'),
    bB: require('../../assets/pieces/xkcd/bB.svg'),
    bN: require('../../assets/pieces/xkcd/bN.svg'),
    bP: require('../../assets/pieces/xkcd/bP.svg'),
  },
};

export function isBoardThemeName(value?: string | null): value is BoardThemeName {
  return BOARD_THEME_OPTIONS.includes(value as BoardThemeName);
}

export function isPieceThemeName(value?: string | null): value is PieceThemeName {
  return PIECE_THEME_OPTIONS.some((theme) => theme.id === value);
}

export function pieceKey(color: 'b' | 'w', type: 'b' | 'k' | 'n' | 'p' | 'q' | 'r'): PieceKey {
  return `${color}${type.toUpperCase()}` as PieceKey;
}
